-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;


CREATE TABLE public.activation_code
(
    id integer NOT NULL ,
    activation_code "char" NOT NULL,
    is_valid boolean NOT NULL,
    validation_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_validate
(
    candidate_id integer NOT NULL,
    validate_id integer NOT NULL,
    PRIMARY KEY (candidate_id)
);

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name "char" NOT NULL,
    last_name "char" NOT NULL,
    nationalty_id character varying(11) NOT NULL,
    birth_year character varying(4) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.companies
(
    company_id integer NOT NULL,
    company_name "char" NOT NULL,
    web_site "char" NOT NULL,
    phone_number "char" NOT NULL,
    PRIMARY KEY (company_id)
);

CREATE TABLE public.company_validate
(
    company_id integer NOT NULL,
    validate_id integer NOT NULL,
    PRIMARY KEY (company_id)
);

CREATE TABLE public.employee_validate_company
(
    company_id integer NOT NULL,
    employee_id integer NOT NULL,
    is_validate boolean NOT NULL,
    PRIMARY KEY (company_id)
);

CREATE TABLE public.employees
(
    user_id integer NOT NULL,
    first_name "char" NOT NULL,
    last_name "char" NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.jobs
(
    id integer NOT NULL,
    job_title "char" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL ,
    email "char" NOT NULL,
    password "char" NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidate_validate
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.candidate_validate
    ADD FOREIGN KEY (validate_id)
    REFERENCES public.activation_code (id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.companies
    ADD FOREIGN KEY (company_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.company_validate
    ADD FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id)
    NOT VALID;


ALTER TABLE public.company_validate
    ADD FOREIGN KEY (validate_id)
    REFERENCES public.activation_code (id)
    NOT VALID;


ALTER TABLE public.employee_validate_company
    ADD FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id)
    NOT VALID;


ALTER TABLE public.employee_validate_company
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (user_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

ALTER TABLE public.companies
    ADD CONSTRAINT "uk_companies"
    UNIQUE ("phone_number");
	
ALTER TABLE public.users
    ADD CONSTRAINT "uk_users"
    UNIQUE ("email");	
	
ALTER TABLE public.candidates
    ADD CONSTRAINT "uk_candidates"
    UNIQUE ("nationalty_id");
	
CREATE SEQUENCE "public"."activation_code_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."activation_code"."id";
	
CREATE SEQUENCE "public"."jobs_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."jobs"."id";

CREATE SEQUENCE "public"."users_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."users"."id";
